### ISSUE TITLE
Feature: Add support for exe in custom shortcuts

### ISSUE THREAD

**Issue by prashasth-nair** [KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher#23]
I have exe file of the games i want them to be listed using custom shortcuts. Please add support for exe files also

**Comment by KrystianLesniak** [comment]
Thank you for your contribution. I will take a look at this feature.

For now, you can create shortcut for .exe inside directory.

**Comment by KrystianLesniak** [comment]
Hello.
I am sorry, after much consideration I have decided not to implement this feature. The reason is that the game shortcuts for GameLauncher are stored in the AppData directory, which according to all guidelines should not contain any non-application related data or binaries. This also means that this directory can be easily deleted by uninstalling an application for example, and I want to prevent users from losing some data.

If you really need to keep exe in this directory I would recommend just creating a shortcut next to and exe in this directory. I do not want to add this feature for users to encourage them to keep exe in that directory, it is mainly meant for shortcuts only.
