### ISSUE TITLE
Feature: Don't show ALL installed games when a query doesn't produce results

### ISSUE THREAD

**Issue by red9350** [KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher#45]
As per title

![image](https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/assets/16651290/8a3eb81f-500b-422f-8bdc-c1d411968c15)

**Comment by KrystianLesniak** [comment]
Hello! Thank you for contribution!

Issue fixed in PR:
https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/pull/46

Generally plugin will not include all results now if global keyword (*) was set for plugin.

I will let you know and close this issue as soon as updated version will be released.

**Comment by KrystianLesniak** [comment]
Yours request applied in the release:
https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/releases/tag/v1.7.2

Update should be available soon in Flow Launcher Plugin Store!
