### ISSUE TITLE
Automatically prefill Custom Shortcuts

### ISSUE THREAD

**Issue by jerrygreen** [KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher#49]
From path like `C:/Games` which most gamers often have.

For example, I ain't seeing Starcraft II and other games from blizzard. GOG games etc.

I know it might sound  uneasy, for example in SC2 folder we have some more executables:

![image](https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher/assets/13215662/6ae6c7f2-c33a-4abe-a269-0b3baa923efc)

Plus, sometimes we have files like `unins000.exe`, `UnityCrashHandler64.exe`, etc. But I think it's possible to find a solution to filter out unnecessary executables.

For example, like with Stacraft II, and many other games, – it's good practice to name your executable the same way the folder named:

```
C:/Games/StarCraft II/StarCraft II.exe
```

So, in most cases it should be fairly easy to determine from what exact executables we need to create links.

Sometimes they might be slightly different though, for example:

```
C;/Games/Project Zomboid/ProjectZomboid32.exe
C;/Games/Project Zomboid/ProjectZomboid64.exe
```

So, there's two other things to take into consideration:

- Obviously, we wanna prefer x64 version (`(?:64)` in regex)
- Plus, the executables don't always have a space in it (gonna put `?` for each space for regex)

I guess there should be a couple regular expressions to test. Something like (pseudo-code):

```js
executableNameRegex = gameFolderName.replaceAll(' ', ' ?') + ' ?(?:\\(?x?64\\)?)?' + '\\.exe'"
```

This takes folder name, optionally checks for `64` `x64` `(64)` `(x64)`, plus ends with `.exe` – a string ready to be used as regex input to iterate through files to find actual game executables.

This way, it should be possible to find 90% of game executables, I think. Automatically.

**Comment by KrystianLesniak** [comment]
Hello @jerrygreen .
Thanks for your contribution!

Regarding your idea, I have developed plugin with strict no guessing policy. That's why I introduced custom shortcuts to allow users to explicitly add games, this allows us not to add game with rule "maybe it's a game, but maybe not, we don't really know". My second concern is that users might not want some plugin to scan all their files and directories 😉. Security Concerns

Regarding GOG games, support is coming soon, and Battle.net is planned for the future.

That said, I am not against the idea of adding a new sync engine designed to search for games from the user's local drive. But it needs to be separated from custom shortcuts, marked as experimental, and disabled by default. And of course this is not the highest priority to work on right now.

I hope this explanation is understandable for you, if you had any questions then go ahead and write.
